### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by yannadani** [chichilicious/awesome-zero-shot-learning#2]
- [x] Add a list of all the papers from major conferences.
- [ ] Create a table of results of all these papers on the major datasets.
- [x] Add link to codes.
- [ ] More blog post links.
- [x] Add a starter/vanilla code as a simple example of walkthrough of zero-shot learning.
- [ ] Extend to other zero-shot learning problems beyond zero-shot classification.

**Comment by DarrenZhangZ** [comment]
The basic codes of paper "Attentive Region Embedding Network for Zero-shot Learning (CVPR2019)" is released at https://github.com/gsx0/Attentive-Region-Embedding-Network-for-Zero-shot-Learning.
